apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: katana-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: katana.local.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: katana-service
            port:
              number: 80
